### ISSUE TITLE
move repo to exist-db?

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/gulp-exist#11]
Should this be moved to exist-db.org here on GitHub?

**Comment by line-o** [comment]
@olvidalo what do you think?

**Comment by olvidalo** [comment]
Not sure... what's the benefit?

Still happy to review and merge any PRs.

**Comment by line-o** [comment]
The only real reason I see, is to then publish it in the @exist-db namespace on npm. I am considering this for node-exist (moving it to the orgs on GitHub and npm).

**Comment by duncdrum** [comment]
Yup, it would increase its visibility. Since tei-publisher (which is still scheduled to move to github last i checked) and now the polymer apps depend upon it, having it in the org would make it easier to track. The NPM namespace was the other reason I had in mind.

**Comment by line-o** [comment]
@olvidalo I think everybody (the community™) would be thankful, if you would still be maintaining this project. ;)

**Comment by duncdrum** [comment]
@olvidalo indeed, you should obviously keep admin rights and the author credit.

**Comment by olvidalo** [comment]
No worries, I wasn't feeling ambushed ;) I was just wondering where this was coming from, so thanks for explaining. 

Would be fine with me.

**Comment by line-o** [comment]
@olvidalo Great!
I am missing the obvious, though: How to do it; Fork to @eXist-db, first?

**Comment by duncdrum** [comment]
@line-o moving is in the repo-settings. I would suggest moving it first, i can add olvidalo as admin very shortly afterwards (if he isn't carried over automatically that is)

**Comment by olvidalo** [comment]
I'll sort #14 out first and then we can get going

**Comment by duncdrum** [comment]
@olvidalo sounds good, @line-o just moved a project yesterday so it should be a bit easier now. I'd suggest to make him co-admin here, and then he can do the transfer, i ll make sure that you stay repo-admin once it's transferred.

**Comment by olvidalo** [comment]
Ok, let's go ahead. Sent an invitation out to @line-o.

**Comment by olvidalo** [comment]
As this is a personal repo, don't think I can give him admin access to transfer it but I'd have to do it myself. @line-o you can try, though. 

@duncdrum the other option would be that you give my temporary access to the exist org so I can create repositories there, then I can do the transfer.

**Comment by duncdrum** [comment]
@olvidalo invite sent, we re in the process of reorganizing our github org, so i need to run a few things by the community before making more sweeping changes. If you d like to permanently become a team member let me know, otherwise you ll be an outside collaborator (with admin) rights for the gulp repo.

**Comment by duncdrum** [comment]
@olvidalo you should now be able to just transfer, if github objects it might be easier to jump on [hip chat](https://www.hipchat.com/gLp8PXSA0) so we can try to figure out whats goin on

**Comment by olvidalo** [comment]
okay, that was easy :)

**Comment by duncdrum** [comment]
@olvidalo thank you for moving. You should have admin rights again, but we might still need to to tweaks some settings for CI and publishing to npm. But its probably best to start separate issues for those.
