### ISSUE TITLE
update readme to gulp 4

### ISSUE THREAD

**Issue by line-o** [eXist-db/gulp-exist#12]
As some commands have changed and gulp v4 is now the standard we should change the documentation or at least have an example in the wiki.

**Comment by olvidalo** [comment]
Sure. Still using gulp 3 but it would be a good occasion to upgrade my projects and learn what's changed. I'll have look. Or, if that'll take too long, feel free to open a PR.

**Comment by line-o** [comment]
@olvidalo I started to update to gulp4 and went down the rabbit hole. Updated a bunch of packages including node-exist and replaced the deprecated package gulp-util. There is one test failing (upload-html5-no-retry) which might be a false negative. But this will rather be a breaking change (major-release).

**Comment by line-o** [comment]
In other words: PR incoming 📥

**Comment by line-o** [comment]
see #13
