### ISSUE TITLE
migrate to travis.com

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/gulp-exist#17]
since the travis.org api has changed we should manually migrate this repo to travis.com by sending an email to support@travis.org  [more info](
https://docs.travis-ci.com/user/open-source-on-travis-ci-com/)

Since there are secret env variable for publishing to npm, @olvidalo would need to do this.

**Comment by line-o** [comment]
We will loose ENV-secrets and build-history. 
The history is not that long and important.
For the environment variables we would have to make changes to switch to a scoped package anyway.

**Comment by duncdrum** [comment]
ok because of problems with travis the repo had to be migrated, sorry for the inconvenience @olvidalo just change ~~`.org`~~ to `.com` and we should be good to go again soon
