### ISSUE TITLE
trigger new release

### ISSUE THREAD

**Issue by line-o** [eXist-db/gulp-exist#33]

**Comment by duncdrum** [comment]
huh? any particular reason

**Comment by line-o** [comment]
To update the docs on npmjs.com

**Comment by duncdrum** [comment]
obviously setting a deploy stage on `.travis.yml` would help. I thought we did this already?

**Comment by line-o** [comment]
#55 might do the trick

**Comment by line-o** [comment]
We still do not see a new version released. 😭

**Comment by line-o** [comment]
What is needed in order to get this to work again? see https://travis-ci.com/eXist-db/gulp-exist/jobs/215236237

**Comment by line-o** [comment]
next attempt with #57

**Comment by line-o** [comment]
This worked. Learning: the commit messages really need to have the correct format.
`fix:` or `fix(component):` instead of `fix ` or `fix (...):`
