### ISSUE TITLE
Separate eXist backend from gulp plugin

### ISSUE THREAD

**Issue by olvidalo** [eXist-db/gulp-exist#4]
@line-o I was thinking of putting the eXist communication stuff into a separate npm package and have gulp-exist use that. Now I saw you made such a package with node-exist a couple of days ago. Did you have something similar in mind? If so I might ditch my plan and just start maintaining a branch using your library as a backend. Any thoughts?

**Comment by line-o** [comment]
Yes you can use node-exist. It was made with that usage in mind. But why have it as a branch?

**Comment by line-o** [comment]
But there is more to come... have you seen that exist has a rest-like API as well? I am currently playing with it, as it allows listings and downloads in a much simpler fashion. This will very likely replace large parts of node-exists RPC calls. Source: https://github.com/wolfgangmm/existdb-node

**Comment by olvidalo** [comment]
I made a branch to play around with it until node-exist is mature and then merge into master. Looking forward for your input on when that would be ;)

It seems to work pretty well though already.

I'm aware of the rest-like APIs and originally I wanted to use them in gulp-exist, but if I remember correctly I couldn't find a way to validate XML wellformedness so I opted for only using RPC as I didn't want to mix APIs. But that's up to personal preference I guess.

**Comment by line-o** [comment]
I see you problem with the limitation of the rest-API.
I think both of them have their use-cases.

> It seems to work pretty well though already.

:+1: You could create a work in progress PR so we can continue this discussion there.
The version number is no indicator for maturity. :)
If you find issues, I would be glad to hear about them.

**Comment by line-o** [comment]
On a side note: The code looks good. And its impressive how fast you picked it up. Had no chance to tell you ^^

**Comment by line-o** [comment]
https://github.com/olvidalo/gulp-exist/pull/5

**Comment by olvidalo** [comment]
it's a good straight forward api and makes the plugin code much more readable. still i'm a little sentimental of letting go of my beautiful async waterfalls :)

**Comment by line-o** [comment]
Sometimes. you need to let an old friend part :)
