### ISSUE TITLE
defineMimeTypes() throws errors

### ISSUE THREAD

**Issue by plutonik-a** [eXist-db/gulp-exist#51]
Defining mime types in the gulpfile like this 
~~~js
const exist = require('@existdb/gulp-exist');

exist.defineMimeTypes({
    'application/xml': ['odd']
});
~~~

throws an error:
~~~
Error: Attempt to change mapping for "odd" extension from "application/xml" to "application/xml".    
Pass `force=true` to allow this, otherwise remove "odd" from the list of  
 extensions for "application/xml".  
[echo]     at Mime.define
~~~

So I followed the advice in the error, went through the relevant mimetype function in module `mime` to check if this is really supported and added the force=true flag like this
~~~js
exist.defineMimeTypes({
    'application/xml': ['odd']
}, true);
~~~
but without any effect.   
In fact, whatever I add or write within `defineMimeTypes` will result in said error.

Never experienced that error before.   
Installed modules:   

- @existdb/gulp-exist 3.0.0
- mime 2.4.4
- node v10.0.0 
- npm 6.9.0 
- gulp 3.9.1 (CLI 2.2.0)

**Comment by line-o** [comment]
@plutonik-a the odd extension is now added by default. That means you can just remove that from your gulp file.

**Comment by plutonik-a** [comment]
Thanks @line-o! I already figured out that removing the odd extension was fixing my problem, but wasn't sure enough if it might be still a bug.

**Comment by line-o** [comment]
OK, closing this then :)

**Comment by line-o** [comment]
added note in #54
