### ISSUE TITLE
feature-request: use repo.xml or package.json for system config params

### ISSUE THREAD

**Issue by JoernT** [eXist-db/gulp-exist#7]
It would be great if we can keep system config params in one place. These are:
- application name (used to name the .xar file)
- version
- authors
- license
- description
- ?

I actually have no strong preference of where to put it - it would be just more convenient to feed the config within the gulpfile with these params and to also token-substitute them in expath.xml and repo.xml

**Comment by olvidalo** [comment]
This would be really useful indeed but I think this task doesn't translate very well into the gulp way of doing things - working with streams of files - so I'm thinking that it shouldn't be part of gulp-exist. Maybe we could have a command line tool for syncing package.json, expath.xml and repo.xml and call that within a gulp task using something like gulp-exec, gulp-shell or gulp-run. Such a tool might be useful outside of the gulp workflow, too...

**Comment by JoernT** [comment]
you're the expert ;) but you get the idea of what i'd like to see. I have no strong opinions of how to achieve that but i dream of a generic gulpfile that covers all the needs we have when building a .xar applications and that's one of it. 

Of course this requires to adhere to certain conventions regarding folder naming etc. but that's more an advantage than the opposite (convention over configuration).

**Comment by line-o** [comment]
@JoernT for an app that is built solely with gulp-exist (including creating the XAR) we could use the package.json.
This would mean to replace placeholders in certain files (repo.xml, ...) with a plugin like https://www.npmjs.com/package/gulp-replace .
Also we need to add the app installation feature from existdb/node-exist to gulp-exist

**Comment by line-o** [comment]
https://github.com/outaTiME/gulp-replace-task seems to be what we want here.

**Comment by duncdrum** [comment]
This seems to be better maintained, https://github.com/Pictela/gulp-token-replace added plus we can configure it to use the same prefix and postfix as ant

**Comment by line-o** [comment]
Yep, looks much better. Since we are using gulp 4 already, we should check also if the plugin is compatible with it.

**Comment by line-o** [comment]
After discussions with @duncdrum and @JoernT and @wolfgangmm `.existdb.json` would also be a valid option to store XAR-package metadata. It already contains server connection info and can easily be extended.

@duncdrum also mentioned to look at the npm package `secrets` (or `dotenv` - my favourite) which looks like a good place to store the sometimes sensitive data like server administrator passwords. I proposed to have it cascaded as such

1. secrets / dotenv
2. .existdb.json
3. package.json
4. maybe even read a build.xml if that's what the project offers

A working prototype for template replacement can be found in [gulp-exist-example](https://github.com/line-o/gulp-exist-example).

**Comment by line-o** [comment]
https://www.npmjs.com/package/@existdb/gulp-replace-tmpl was created to achieve the template replacement part.

The cascading can be achieved by reading all 4 options above and then constructing and array with objects of them in that order

```js
// .tmpl replacements to include 
// an array of objects the first definition of a key wins
const replacements = [packageMetadata, {version, license}]
```
