### ISSUE TITLE
Gulp generates files as collections in eXist

### ISSUE THREAD

**Issue by wronaa** [eXist-db/gulp-exist#8]
Hello, based on the tutorial from https://github.com/cceh/papyri 
at the command "gulp deploy-local" 
gulp generates the files and folders as collections in eXist
instead of saving it in apps/<project folder>
Any suggestions for a solution?

eXist Version is 2.2

![screenshot exist mit gulp](https://cloud.githubusercontent.com/assets/9029108/15475238/5cf79860-2109-11e6-87db-fc83f9b147d6.jpg)

**Comment by jblumtritt** [comment]
Same thing here. When running gulp deploy eXist creates a top level collection for every resource/collection. The urlencoded path is treated as the collection's name.

![gulp-exist-collection-browser](https://cloud.githubusercontent.com/assets/3205396/15650874/057eff92-267c-11e6-91b3-07842bdeb66b.jpg)
